//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TccSenai
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFornecedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFornecedor()
        {
            this.tblContato = new HashSet<tblContato>();
            this.tblFornecedorItem = new HashSet<tblFornecedorItem>();
            this.tblRecebimentoGerencial = new HashSet<tblRecebimentoGerencial>();
            this.tblRecebimentoNf = new HashSet<tblRecebimentoNf>();
        }
    
        public int idFornecedor { get; set; }
        public string inscricaoEstadual { get; set; }
        public string nomeFantasia { get; set; }
        public string razaoSocial { get; set; }
        public string responsavel { get; set; }
        public string cep { get; set; }
        public string bairro { get; set; }
        public string logradouro { get; set; }
        public string numero { get; set; }
        public string municipio { get; set; }
        public string uf { get; set; }
        public string cnpj { get; set; }
        public int idAvaliacao { get; set; }
    
        public virtual tblAvaliacao tblAvaliacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblContato> tblContato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFornecedorItem> tblFornecedorItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRecebimentoGerencial> tblRecebimentoGerencial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRecebimentoNf> tblRecebimentoNf { get; set; }
    }
}
