//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TccSenai
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPosicaoEstoque
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPosicaoEstoque()
        {
            this.tblProduto = new HashSet<tblProduto>();
        }
    
        public int idPosicao { get; set; }
        public string rua { get; set; }
        public string bloco { get; set; }
        public string andar { get; set; }
        public string apartamento { get; set; }
        public string posicaoEstoq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduto> tblProduto { get; set; }
    }
}
