//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TccSenai
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRecebimentoNf
    {
        public int idRecebimentoNf { get; set; }
        public string numeroNf { get; set; }
        public System.DateTime dataEmissao { get; set; }
        public int idFornecedor { get; set; }
        public int idItemRecebido { get; set; }
    
        public virtual tblFornecedor tblFornecedor { get; set; }
        public virtual tblItemRecebido tblItemRecebido { get; set; }
    }
}
