//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TccSenai
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTipoGrupo
    {
        public int idTipoGrupo { get; set; }
        public int idTipo { get; set; }
        public int idGrupo { get; set; }
    
        public virtual tblGrupo tblGrupo { get; set; }
        public virtual tblTipo tblTipo { get; set; }
    }
}
